### ISSUE TITLE
Internal Error using commands that call the GUI

### ISSUE THREAD

**Issue by metzrock** [aleksilassila/Islands#19]
Hello! Whenever I try to use a command that calls the gui like /is create or /is moderate an internal server error occurs. This only began happening once I installed a shop plugin called Auto Tune that also utilizes a GUI, I'm going to report this bug to them as well. I can still operate the GUI on the shop plugin, just not islands anymore. I don't know anything about plugins, but it's like Islands is looking for GUI info but for some reason it looks for it in the AutoTune plugin that shares "com.github.stefvanschie.inventoryframework.pane.Pane".

[https://pastebin.com/hBfcRD3j](url)

`[22:21:15 INFO]: AjMcAjface issued server command: /is create
[22:21:15 WARN]: [Islands] Loaded class com.github.stefvanschie.inventoryframework.pane.Pane from Auto-Tune v0.13.0-pre-release-4 which is not a depend, softdepend or loadbefore of this plugin.
[22:21:15 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin Islands v5.0.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-532]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-532]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-532]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2023) ~[patched_1.16.5.jar:git-Paper-532]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1838) ~[patched_1.16.5.jar:git-Paper-532]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1791) ~[patched_1.16.5.jar:git-Paper-532]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-532]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-532]        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-532]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-532]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-532]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-532]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-532]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1140) ~[patched_1.16.5.jar:git-Paper-532]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-532]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-532]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1269) ~[patched_1.16.5.jar:git-Paper-532]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.5.jar:git-Paper-532]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-532]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void com.github.stefvanschie.inventoryframework.pane.StaticPane.addItem(com.github.stefvanschie.inventoryframework.gui.GuiItem, int, int)'
        at me.aleksilassila.islands.GUIs.CreateGUI.availableIslandPanes(CreateGUI.java:69) ~[?:?]
        at me.aleksilassila.islands.GUIs.CreateGUI.getMainGui(CreateGUI.java:47) ~[?:?]
        at me.aleksilassila.islands.GUIs.GUI.open(GUI.java:24) ~[?:?]
        at me.aleksilassila.islands.commands.subcommands.CreateSubcommand.openGui(CreateSubcommand.java:23) ~[?:?]
        at me.aleksilassila.islands.commands.AbstractCreateSubcommands.onCommand(AbstractCreateSubcommands.java:28) ~[?:?]
        at me.aleksilassila.islands.commands.IslandCommands.onCommand(IslandCommands.java:106) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-532]
        ... 19 more`

**Comment by aleksilassila** [comment]
That's weird indeed, seems like my plugin is trying to use their (really old) version of inventoryframework library, even though it has newer version packed inside the jar. Not sure what can I do, but they should update their IF library version for sure :,) Let me know if they respond to you
