### ISSUE TITLE
 Could not pass event InventoryClickEvent to Islands v5.0.3

### ISSUE THREAD

**Issue by Pixelfool** [aleksilassila/Islands#21]
I am having this strange error, where non oped users cant create islands.
When they click on any biome, the next window opens but there are no books to click on for the size.
![Screenshot](https://user-images.githubusercontent.com/53619220/111915446-9e354f80-8a76-11eb-8f05-8a75063bb671.png)
If they click on the empty buttons, the following error is triggered:

 [Server thread/ERROR]: Could not pass event InventoryClickEvent to Islands v5.0.3
java.lang.NullPointerException: null
	at com.github.stefvanschie.inventoryframework.pane.PaginatedPane.click(PaginatedPane.java:223) ~[?:?]
	at com.github.stefvanschie.inventoryframework.gui.InventoryComponent.click(InventoryComponent.java:202) ~[?:?]
	at com.github.stefvanschie.inventoryframework.gui.type.ChestGui.click(ChestGui.java:111) ~[?:?]
	at com.github.stefvanschie.inventoryframework.gui.GuiListener.onInventoryClick(GuiListener.java:66) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor227.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-553]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-553]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-553]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2542) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1140) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1094) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1008) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-553]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by aleksilassila** [comment]
Hi,

Since opd players can create islands, I assume the issue is with your permissions. For a player to be able to create an island, they need `islands.command.create` and `islands.command.create.normal` permissions for normal island size for instance. You can see the full list of permissions [here](https://github.com/aleksilassila/Islands/wiki/Commands-And-Permissions).

About the error in the console, do you by any chance happen to use any other plugin that also uses InventoryFramework? I could have a look at your plugin list if you could post it here.

**Comment by Pixelfool** [comment]
Thanks. It was a permissions problem. I feel so dumb.
