### ISSUE TITLE
Can't use /is create unless given operator

### ISSUE THREAD

**Issue by SniparsZach** [aleksilassila/Islands#29]
Whenever someone with no permissions runs the command /is create, I get this error when choosing an island biome size.

`[Server thread/ERROR]: Could not pass event InventoryClickEvent to Islands v5.0.8
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2427) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:55) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:11) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1125) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "java.util.Map.get(Object)" is null
	at com.github.stefvanschie.inventoryframework.pane.PaginatedPane.click(PaginatedPane.java:223) ~[?:?]
	at com.github.stefvanschie.inventoryframework.gui.InventoryComponent.click(InventoryComponent.java:202) ~[?:?]
	at com.github.stefvanschie.inventoryframework.gui.type.ChestGui.click(ChestGui.java:111) ~[?:?]
	at com.github.stefvanschie.inventoryframework.gui.GuiListener.onInventoryClick(GuiListener.java:66) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
	... 18 more
`

**Comment by SniparsZach** [comment]
PERMISSIONS ISSSUE

islands.commands.create.* solved it
