### ISSUE TITLE
Error when loading commands

### ISSUE THREAD

**Issue by pokemonrocks9** [aleksilassila/Islands#34]
Not sure the cause but the error kicked is [13:34:30] 
[Server thread/INFO]: [Islands] Initialising commands and configuration
[13:34:30] [Server thread/WARN]: [Islands] Task #111 for Islands v5.0.9 generated an exception
java.lang.IllegalArgumentException: No enum constant org.bukkit.block.Biome.SNOWY_TUNDRA
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at org.bukkit.block.Biome.valueOf(Biome.java:11) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at me.aleksilassila.islands.IslandsConfig$Entry.<init>(IslandsConfig.java:360) ~[islands.jar:?]
	at me.aleksilassila.islands.IslandsConfig.loadEntries(IslandsConfig.java:75) ~[islands.jar:?]
	at me.aleksilassila.islands.IslandsConfig.getConfig(IslandsConfig.java:59) ~[islands.jar:?]
	at me.aleksilassila.islands.Islands.initialise(Islands.java:125) ~[islands.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-"901fd94"]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-"901fd94"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-"901fd94"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-"901fd94"]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by pokemonrocks9** [comment]
This appears to happen when updating from 1.17 to 1.18, Snowy Tundra and Wooded Hills biomes in islands.yml causes it to stop loading

**Comment by aleksilassila** [comment]
Seems like the changes in biome names in 1.18 is causing this. I'll push a fix soon, in the meantime you can replace the old biomes with their new counterparts by hand
