### ISSUE TITLE
Visit command throws npe

### ISSUE THREAD

**Issue by barrettford** [aleksilassila/Islands#8]
[01:21:44] [Server thread/INFO]: barrett_ford issued server command: /visit
--
[01:21:44] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'visit' in plugin Islands v4.7.3
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-256]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-256]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-256]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2005) ~[patched_1.16.4.jar:git-Paper-256]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1816) ~[patched_1.16.4.jar:git-Paper-256]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1769) ~[patched_1.16.4.jar:git-Paper-256]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-256]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-256]
at  net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)  ~[patched_1.16.4.jar:git-Paper-256]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-256]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-256]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-256]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-256]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1135) ~[patched_1.16.4.jar:git-Paper-256]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.4.jar:git-Paper-256]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-256]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.4.jar:git-Paper-256]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.4.jar:git-Paper-256]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-256]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: java.lang.NullPointerException
at java.util.UUID.fromString(UUID.java:192) ~[?:1.8.0_272]
at me.aleksilassila.islands.GUIs.VisitGUI.getPanes(VisitGUI.java:76) ~[?:?]
at me.aleksilassila.islands.GUIs.VisitGUI.getGui(VisitGUI.java:31) ~[?:?]
at me.aleksilassila.islands.GUIs.PageGUI.open(PageGUI.java:27) ~[?:?]
at me.aleksilassila.islands.commands.TeleportCommands$VisitCommand.onCommand(TeleportCommands.java:57) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-256]
... 19 more

**Comment by aleksilassila** [comment]
Fixed in next release
